### ISSUE TITLE
Missing ReadMe

### ISSUE THREAD

**Issue by gelistir** [vdemydiuk/mtapi#1]
Hello,
Can you provide a readme file for your code? I am not be able to build it with VS2013. Maybe, you can list some dependencies. Thanks in advance.

**Comment by vdemydiuk** [comment]
Hi!
I will create solution files for VS2013 and VS2015 soon.

**Comment by shuherus** [comment]
Hello,
Could you please include a readme file on how to get started with the project?
Cheers

**Comment by vdemydiuk** [comment]
I have added readme file. It will be updated with more information soon.
