### ISSUE TITLE
Add to MtApi5:    GetLastError() , ResetLastError()

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#100]
https://www.mql5.com/en/docs/check/getlasterror
https://www.mql5.com/en/docs/common/resetlasterror

These are important functions because AccountInfoInteger and the other same functions do not return an error.

Maybe it is still possible to add the 2nd variant of the functions with Bool as a return?

![grafik](https://user-images.githubusercontent.com/17534012/37055470-195a0932-2182-11e8-8ca9-55ea44c2b72f.png)

Thanks

**Comment by vdemydiuk** [comment]
I will add function GetLastError and ResetLastError in next version.
Also I will add second function SymbolInfoString.
