### ISSUE TITLE
Bug?  in MtApi5 SeriesInfoInteger() return     int<->long

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#102]
![grafik](https://user-images.githubusercontent.com/17534012/37114563-0edbf944-2249-11e8-841d-d66e32bed8ef.png)

![grafik](https://user-images.githubusercontent.com/17534012/37114660-3aa3c25a-2249-11e8-941b-d1f7b78e6430.png)

I get an Error from Matlab with Source: MtApi

Error using cntMt5Api_timeseries/SeriesInfoInteger (line 31)
Message: Die angegebene Umwandlung ist ungültig.
Source: MtApi5
HelpLink:

**Comment by vdemydiuk** [comment]
Yes, this is bug. It will be fixed to long in next version of MtApi5.
