### ISSUE TITLE
MtApi5:  rename OrderCloseALL() -> PositionCloseALL()

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#107]
I found a litle missmatch .
In mt5 orders and positions are treated separately.

Please rename the function

**Comment by vdemydiuk** [comment]
I have added function 
int PositionCloseAll()
that closes all open positions and return count of them.

Function OrderCloseAll set as deprecated. It makes no sense in MT5 and it was copied from MtApi MT4.
It's not possible to close an Order in MT5 since Orders become (or add/subtract to) Positions.
