### ISSUE TITLE
MtApi5: add function    OrderCloseALL()

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#108]
Similar to the function PositionCLoseALL()

**Comment by vdemydiuk** [comment]
I have left old function OrderCloseAll as deprecated in MtApi MT5.
According to issue #107:
"Function OrderCloseAll set as deprecated. It makes no sense in MT5 and it was copied from MtApi MT4.
It's not possible to close an Order in MT5 since Orders become (or add/subtract to) Positions."
