### ISSUE TITLE
OrderModify Failed

### ISSUE THREAD

**Issue by Perens28** [vdemydiuk/mtapi#112]
Hi,
I have a little problem with OrderModify.  It´s failed. But If I use it in try{} block its sometimes work. Can I someone get error why its failed ? Thanks

**Comment by KptKuck** [comment]
Hello Perens28,
to solve the problem it is necessary to get more information.
Take screenshots or send code, log entrys from Metatrader.

**Comment by Perens28** [comment]
Yep, I am sorry I get OrderModify error 130..

A try very simple way se SL to my orders.  On some orders it works a for some doesnt.

Here is the code

` var orders = mainWindow.apiclient.GetOrders(MtApi.OrderSelectSource.MODE_TRADES);
                if(orders != null && orders.Any())
                {
                    int e = 0;
                    foreach(var order in orders)
                    {
                        Ticket[e] = order.Ticket;
                        
                        if (e == 0) FirstPrice = order.OpenPrice;
                        
                        //mainWindow.textbox.Text = FirstPrice.ToString() + "\r\n";
                        Bid = mainWindow.apiclient.SymbolInfoTick("GOLD").Bid;
                        try

                        { if (order.Operation == MtApi.TradeOperation.OP_SELL && order.OpenPrice - 0.10 > Bid && order.StopLoss == 0) mainWindow.apiclient.OrderModify(order.Ticket, 0, order.OpenPrice - 0.10, 0, DateTime.MinValue); }
                        catch
                        {
                            mainWindow.textbox.Text += "SL Failed " + order.Ticket.ToString() + "\r\n";
                        }  
                         e++;
                    }
                }`

My broker havent limits to SL.. 

Thanks

**Comment by Perens28** [comment]
Yea I changed Bid for Ask. My fault, Thanks

**Comment by vdemydiuk** [comment]
Can we close this issue?

**Comment by KptKuck** [comment]
I think so
