### ISSUE TITLE
Log4Net:   change logfile extension to "log" 

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#113]
Is it possible to change the extension?

Most editors like VS Code or NotePad++ release all options only with the log extension.

Thanks

**Comment by vdemydiuk** [comment]
Hi!
Yes, I will change it to 'txt'.

**Comment by KptKuck** [comment]
Curently it is "txt" 
change it to "log"

**Comment by vdemydiuk** [comment]
:) My mistake. Sure, I will change to log.
