### ISSUE TITLE
MtApi5: TesterMode ,correct working deinitExpert() ?  

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#114]
I am a bit confused.

In the conversation about issue #16  , the last thing is:

A workaround is built in which simulates deinit after 2 seconds with no quotes.

I press stop in the tester and Matlab gets a connection changed event.
Immediately and not after 2 seconds.
Also the TestClient disconnected immediately.
This shows me a correct behavior.

Nevertheless, the logger fills in entries with timeouts.
![image](https://user-images.githubusercontent.com/17534012/38165827-125d226c-351a-11e8-81a0-231e8d9871ae.png)

> 2018-03-31 19: 02: 19,710 [4] WARN MTApiService.MtExpert - Mt5Expert has received new tick during 2 sec in testing mode. The possible cause: user has stopped the tester manually in MetaTrader 5.

What is active now?
incorrect Timeout function  or a correct deinitExpert function or both ?

**Comment by vdemydiuk** [comment]
I will investigate it soon. Maybe MetaQuotes changed behavior of stop button.

**Comment by vdemydiuk** [comment]
Fixed it by commit 1a5882b75a784ce42d4154219e317413bc04100b . Now it is working as designed (with delay 2 sec).
