### ISSUE TITLE
Can I use IP to access metatrader remotely

### ISSUE THREAD

**Issue by li0803** [vdemydiuk/mtapi#12]
i try to use like below screenshot. But I get a "EndpointNotFoundException" error.
![408354ec8379f30f](https://cloud.githubusercontent.com/assets/491759/17847735/3120fe6e-6882-11e6-9803-ebce2bda46ed.jpg)

Can I run my metatrader on a server, and connect to it from another machine using ip

Thanks

**Comment by vdemydiuk** [comment]
yes, you can use remote connection to MetaTrader using IP.
But IP is not needed if you are working localy,
