### ISSUE TITLE
GetLastErrorString for Mt4Api

### ISSUE THREAD

**Issue by darcome** [vdemydiuk/mtapi#123]
Hi,

is it possible to have a funnction that returns the string error based on the value of GetLastError?

Thanks in advance,
Luca

**Comment by vdemydiuk** [comment]
Hi.
MQL5 does not have function ErrorDescription like MQL4. So there is only one way to implement this function: add it manually to MtApi and copy all descriptions from tables
https://www.mql5.com/en/docs/constants/errorswarnings/enum_trade_return_codes
https://www.mql5.com/en/docs/constants/errorswarnings/errorcodes
I will do it in next release.

**Comment by darcome** [comment]
I am sorry, I didn't know Mt4Api already had an ErrorDescription function.
I am happy with that :)

Thank you,
Luca
