### ISSUE TITLE
MT4 AccountProfit() returning always zero value

### ISSUE THREAD

**Issue by gonzsanc** [vdemydiuk/mtapi#124]
Hello. I am using VS2017 and c# for Metatrader 4.

This instruction always return zeros, on both demo and live accounts:

`txtAccountProfit.Text = string.Format(CultureInfo.GetCultureInfo("en-US"), "{0:N2}", _apiClient.AccountProfit());`

It happens because `_apiClient.AccountProfit()` always returns 0

I have tested other `MtApiClient` account methods and they are running fine.

**Comment by vdemydiuk** [comment]
Hi,
I will check this problem and fix it soon in next version.

**Comment by peterpuglisi** [comment]
I don't think this is a bug with MtApi at all, calling AccountProfit() from an MT4 script will return 0 if there are no active trades in the Trade tab and doesn't take into account trades in the Account History. Check if Profit value in your "Trade" tab is also zero.

**Comment by vdemydiuk** [comment]
I have tested this issue also and did not found that this is a bug (same behavior in MQL).
I am closing it.
