### ISSUE TITLE
Performance, Multiple Symbols

### ISSUE THREAD

**Issue by glikoz** [vdemydiuk/mtapi#126]
Hi @vdemydiuk,

 thank you for this project first, I have  questions about this great project:

- Have you ever think to use ZeroMQ or NamedPipe for messaging between MT4 and .NET, could we get performance gain using zmq or named pipe? Or TCP implemantation is enough?

https://github.com/dingmaotu/mql-zmq
https://github.com/darwinex/DarwinexLabs/blob/master/tools/MQL4/ZeroMQ_MT4_EA_Template.mq4

- Is it better to seperate "Send Tick Data" and "Execute Command" parts?
Because I will tick 10 symbols from MT4 to .Net Side.
But only one Command Executer is enough to execute command that sends from .NET side.
(portfolio based starategy)

Thanks again.

**Comment by KptKuck** [comment]
I think the connection is fast enough.
Here is a test with Matlab and Mt5
AMD Ryzen 1800x

Get the tick one hundred times = 120ms






tic
  for idx=1:1:100
    [result_ok ,MqlTick] = api.cMarketInfo.SymbolInfoTick('EURUSD');
  end
toc

end

'
>> cntMt5Api_speedtestMarketInfo(api)
Elapsed time is 0.120614 seconds.
'

**Comment by glikoz** [comment]
Thx
