### ISSUE TITLE
How does this work with Metatrader?

### ISSUE THREAD

**Issue by eaba** [vdemydiuk/mtapi#130]
Hi all,
I am a newbie and I want to understand how this repo can me automate trading with MetaTrader terminal.
Any Demo video?

**Comment by KptKuck** [comment]
This Repo is an API for Metatrader 
[https://en.wikipedia.org/wiki/Application_programming_interface](url)

**Comment by alexssource** [comment]
Hi @eaba!
Using this API you can write the experts for MetaTrader using c# language and all power of the .Net framework

**Comment by alexssource** [comment]
Hi @eaba!
Yes, the mtapi.ex4 runs on metatrader. It opens the specified port with which the C# client will work.
As I understand, yes, we can discuss with the MetaTrader **almost** in real-time (if I understood right this API is asks the tasks queue if there is taks to run, so depends on delay it can be some milliseconds to sleep). Hope it helps!

**Comment by KptKuck** [comment]
> 
> 
> Hi @eaba!
> Yes, the mtapi.ex4 runs on metatrader. It opens the specified port with which the C# client will work.
> As I understand, yes, we can discuss with the MetaTrader **almost** in real-time (if I understood right this API is asks the tasks queue if there is taks to run, so depends on delay it can be some milliseconds to sleep). Hope it helps!

You're confusing something
Gitter Channel -> https://gitter.im/

**Comment by alexssource** [comment]
Hi @KptKuck 
Yes, you are right 👍 
Sorry @eaba . I never heard about gitter before

**Comment by vdemydiuk** [comment]
There is demo video about MtApi:
https://www.youtube.com/watch?v=QNpG4IXokLE&t=

Many thanks to **Jason Lee** for it.
