### ISSUE TITLE
orderSend method return error code 10021,how do it?

### ISSUE THREAD

**Issue by xuanyuan1hao** [vdemydiuk/mtapi#131]
my code like this:

MqlTradeRequest mqlTradeRequest = new MqlTradeRequest();
mqlTradeRequest.Symbol = "EURUSD";
mqlTradeRequest.Comment = "tt";
mqlTradeRequest.Volume = 0.1;
mqlTradeRequest.Type = ENUM_ORDER_TYPE.ORDER_TYPE_BUY;
mqlTradeRequest.Price = 1.17655;
mqlTradeRequest.Action = ENUM_TRADE_REQUEST_ACTIONS.TRADE_ACTION_DEAL;
mqlTradeRequest.Type_time = ENUM_ORDER_TYPE_TIME.ORDER_TIME_GTC;
MqlTradeResult result = null;
var ok = _mtApiClient.OrderSend(mqlTradeRequest, out result);
Console.WriteLine(result);

return result is following :
result = {Retcode=10021; Comment=No prices; Deal=0; Order=0; Volume=0; Price=0; Bid=0; Ask=0; Request_id=0}

**Comment by KptKuck** [comment]
Look at this page for Error Codes.
https://www.mql5.com/en/docs/constants/errorswarnings/enum_trade_return_codes
10021 says "No Prices" .
Metatrader has no price data.
Its an error from Metatrader not MtApi

**Comment by xuanyuan1hao** [comment]
thanks, i just do it!
