### ISSUE TITLE
MtApi5: ENUM_POSITION_PROPERTY_DOUBLE remove POSITION_COMMISION

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#138]
This element does not exist in the current version.

![grafik](https://user-images.githubusercontent.com/17534012/50735795-a74ae680-11b4-11e9-9ee2-803907f6bb16.png)

https://github.com/vdemydiuk/mtapi/blob/f01ec01a5f3f81d64d0ba2c7252734d54e30343a/MtApi5/Mt5Enums.cs#L551

**Comment by vdemydiuk** [comment]
Ok. It will be removed in next version.
