### ISSUE TITLE
Implement PositionClose into MtApi (MT5)

### ISSUE THREAD

**Issue by wesleyteixeira** [vdemydiuk/mtapi#14]
https://www.mql5.com/en/docs/standardlibrary/tradeclasses/ctrade/ctradepositionclose

**Comment by wesleyteixeira** [comment]
I'm testing the implementation and soon I will make the pull request

**Comment by wesleyteixeira** [comment]
#15

**Comment by vdemydiuk** [comment]
Hello.
I will implement it after release MtApi (MT4) version 1.0.30.

**Comment by arteny** [comment]
Then PositionOpen (and/or OrderOpen) will be meaningful as well

**Comment by vdemydiuk** [comment]
I have implemented function PositionOpen. 
Commit cacc0ea787198c877b50c30483840f6552bd9b27

**Comment by arteny** [comment]
If we have PositionOpen, then we need ResultRetcode and ResultDeal functions, else how we can get know the result of operation?

> Успешное окончание работы метода PositionOpen(...) не всегда означает успешное совершение торговой операции. Необходимо проверять результат выполнения торгового запроса (код возврата торгового сервера) вызовом метода ResultRetcode(), а также значение, возвращаемое методом ResultDeal().

**Comment by vdemydiuk** [comment]
I will implement function PositionOpen which will encapsulate MQL functions PositionOpen, ResultRetcode, ResultDeal.
