### ISSUE TITLE
Abnormal Termination

### ISSUE THREAD

**Issue by Kimo11335** [vdemydiuk/mtapi#154]
Hello,
When using mtapi in the backtest on MT4,
I get this error, Abnormal Termination.
I tried uninstall then reinstall, but did not help.
after pushing start in Back test mode, the graph is standing still.
It was working all of the day, but then it stopped working.
I don't know if this is helpful, but maybe you have a workaround, or an idea where to investigate.
Thanks
KG

**Comment by Kimo11335** [comment]
More Info
After bush start in the Mt4 BackTest
In the "Journal" Waiting on remote Client.

I the visual studio 2015 I get this error
An exception of type 'MtApi.MtExecutionException' occurred in MtApi.dll but was not handled in user code
I stop the firewall to test if that is the problem, but that did not help.
this is the exception message "Response from MetaTrader is null"

Mt4"Journal" saying "waiting on remote client..."
and yes I am sure that I am using the correct Port :-)

**Comment by Kimo11335** [comment]
It seems that the problem only exist with Backtesting, but not on life Data Chart.

**Comment by Kimo11335** [comment]
Ok....
It's working now.
in the visual studio "Add reference", Newtonsoft.Json and MtApi, was added again.
now when client connect, the backtest begins to run.
Thanks for a great project :-)

**Comment by Kimo11335** [comment]
I am running into this strange problem, I am running VS2015 in debug mode.
but the application runs for 30 sec, then just"puff" terminates, no exception, no nothing.
as if I had an "application.close" command.
have you experienced this?

**Comment by Kimo11335** [comment]
sorry guys, my mistake, their was "End" in the code.

**Comment by vdemydiuk** [comment]
Okay. I am closing this issue.

**Comment by Kimo11335** [comment]
Thank you
