### ISSUE TITLE
How To Create Broker?

### ISSUE THREAD

**Issue by hitjariwala** [vdemydiuk/mtapi#155]
Hi,

Can you guide me how to create broker and client using api?

Thanks

**Comment by vdemydiuk** [comment]
Hi.
I am not sure that I understand your question.
MtApi can work with existing connection to the broker using MetaTrader terminal as bridge.
MtApi can't work with MetaTrader servers directly.

**Comment by eabase** [comment]
Maybe just close all these kind of issues?
