### ISSUE TITLE
Implement Backtesting into MtApi for MetaTrader 5

### ISSUE THREAD

**Issue by wesleyteixeira** [vdemydiuk/mtapi#16]

**Comment by vdemydiuk** [comment]
Hello.
I will add backtesting after release MtApi (MT4) version 1.0.30.

**Comment by vdemydiuk** [comment]
I have started to work on backtesting in separate branch mtapi5_backetesting and I have found two big problems: 
- Expert does not have window handle in test mode. In this case it can't receive any commands from MtApi client.
- Expert does not receive OnDeinit event if user press button Stop during work tester.

I will continue to inverstigate these problems and if I find solitions I will merge backtesting into master branch.

**Comment by arteny** [comment]
Does backtesting mean using MT5 Strategy Tester?
In this case only problem in my understanding to provide client's parameters to MtApi expert (in order to use them from Parameters tab of Strategy Tester).
Now it shows only one parameter - Port, which is MtApi parameter itself, but how to provide own parameters..
Of course I am not familiar with backtesting, so looking carefully for your investigation.

**Comment by vdemydiuk** [comment]
yes, it means to use Stratedy tester.
I am investigating how to emulate OnDeinit event.

**Comment by arteny** [comment]
How is it going? When it can be expected?

**Comment by vdemydiuk** [comment]
I want to complete some issues of MtApi4 then return back to this issue (and other related MtApi5).

**Comment by arteny** [comment]
Which dates we can expect this feature?

**Comment by vdemydiuk** [comment]
Difficult to say, This is not trivial task and I think I needs to use Windows API to implement it. So I think it will be in the end this month,

**Comment by vdemydiuk** [comment]
I have added class Mt5Expert into MTApiService that emulates deinit event if it is not receiving ticks during 2 sec. This emulation fixes problem when user stopped testing manually by button "Stop".

**Comment by arteny** [comment]
Please, explain how to use BackTesting in MtApi5? I didn't find any OnTick event.
