### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.json, Version=8.0.0.0, Culture=neutral, Public Key=30ad4fe6b2a6aeed' 

### ISSUE THREAD

**Issue by kamranmasud** [vdemydiuk/mtapi#160]
I am using this .net mt api https://github.com/vdemydiuk/mtapi/ in vbscript...When i am trying to connect to mt4, error occurs i.e 
Could not load file or assembly 'Newtonsoft.json, Version=8.0.0.0, Culture=neutral, Public Key=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

I have referenced all the dll files..When i run this project in visual studio c# , it works but when i try to write my vbscript and calling the connect method, vbscript shows this error.. Can anyone tell me how to solve this?

**Comment by vdemydiuk** [comment]
I have updated library Newtonsoft.json in MtApi to version 11.0.0.0.
Please check all references in your project to this library.
