### ISSUE TITLE
log file in MTApiService is too large

### ISSUE THREAD

**Issue by zhao0876** [vdemydiuk/mtapi#168]
After I connected 7-8 MT4 and passed a night
I found my C drive is full.
then I found  the log file of MTApiService in the temp directory 
When it is added to 1G, a new one will be created.
So I have about 15G log files.
I have  modified MTApiService and removed all log output.
I also report this to you.
There is too much information   outputed . In addition to the large log file, it also affects performance
And it's in the temp directory, no one will find and use it

**Comment by vdemydiuk** [comment]
Hi.
Are you using debug or release configuration?

Really, MtApi writes a lot of information in debug mode. But log file contains min information (warning or errors) in release mode. All debug information must be skipped for release.
