### ISSUE TITLE
Is it possible to disable logging?

### ISSUE THREAD

**Issue by darcome** [vdemydiuk/mtapi#169]
Hi, is it possible to disable logging? THe only thing I saw related to logging is MtApiService.LogConfigurator.Setup, but you can only specify a file name... What if I want to disable logging?

Thanks in advance

**Comment by vdemydiuk** [comment]
Hi.
There is no way to disable logging or to setup level of the logging.
It has predefined levels:
debug configuration - Level.Debug
release configuration - Level.Info
But I can add function Setup with extended parameters into LogConfigurator which allows to define log level by user.
Is it good solution for you?

**Comment by darcome** [comment]
Hi, I asked for it because since I am using 9 MtApi instances at the same time, my app ends up with like 100 threads blocking each other trying to write logs...
In any case I have now written my own library using just a socket server / client implementation so I don't need MtApi anymore.

However, thanks for the time and effort spent into MtApi!
