### ISSUE TITLE
why keep mq4 and mq5 content different?

### ISSUE THREAD

**Issue by mhamri** [vdemydiuk/mtapi#171]
metaquote updated mql4 language to support mql5 new features. so I wonder why the content of mq4 (https://github.com/vdemydiuk/mtapi/tree/master/mq4) and mq5 (https://github.com/vdemydiuk/mtapi/tree/master/mq4) file is different. also, the mql4 updated 3 years ago, while mql5 is updated 3 months ago. there should be a way to carry backward the new features is added to mql5 file

**Comment by vdemydiuk** [comment]
I am not sure that it has sense to make one MQL for both platform. If we will use MtApi5.mq5 for MT4 it will take a lot of time to testing it under this terminal.
In my opinion it is more easy support two MQL files at this moment. 
And I hope MT4 will be closed soon.
