### ISSUE TITLE
How to get the text from the popup alert or expert advisors terminal?

### ISSUE THREAD

**Issue by FabioAlbano** [vdemydiuk/mtapi#178]
I have to catch the text when my indicator show an alert, I was doing by the log file, but maybe there's a solution in this API. I checked OnChartEvent, but I'm lost... Can someone help?
Thank you!

**Comment by vdemydiuk** [comment]
Hi.
Can you contact with me via private channel (or via skype, email) and we will discuss your task.

**Comment by FabioAlbano** [comment]
Hi! Sorry I didn't close before, I already solved saving EA alert into a file.
