### ISSUE TITLE
Cannot find any way to access ACCOUNT_TRADE_MODE

### ISSUE THREAD

**Issue by cychrn** [vdemydiuk/mtapi#185]
Hello Vdemydiuk,

I tried to find a way to get Account type whether it is DEMO or REAL account but i cannot find ACCOUNT_TRADE_MODE any where...

Could you please advise how to check Account type in MtApi4?

Thank you very much!

**Comment by KptKuck** [comment]
This ENUM Is only available in MtApi5
https://github.com/vdemydiuk/mtapi/blob/a4df4bbf1ec5f6181f29d27770d727b44c3f9b06/MtApi5/Mt5Enums.cs#L363

**Comment by cychrn** [comment]
i see... so is there any other way to check if the account is real or demo using MtApi for MT4?

**Comment by KptKuck** [comment]
> 
> 
> i see... so is there any other way to check if the account is real or demo using MtApi for MT4?

No, unfortunately not.
Mt4 dies slowly, but jump to mt5?

**Comment by vdemydiuk** [comment]
There is function in MtApi (MT4)
        public bool IsDemo()
And it calls related function of MQL4 - IsDemo:
https://docs.mql4.com/check/isdemo

Is it that you need?

**Comment by cychrn** [comment]
Yes thank you very much!!
