### ISSUE TITLE
MtApiClient::GetOrders() problem

### ISSUE THREAD

**Issue by ghost** [vdemydiuk/mtapi#187]
Hello, Vdemydiuk

While running TestApiClientUI, the error occurred.
"Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified."
How can I fix this?

Thank you.

**Comment by RWanted** [comment]
![image](https://user-images.githubusercontent.com/45385959/71091644-d18c8d00-21e8-11ea-9a75-0189fb948b6e.png)

**Comment by vdemydiuk** [comment]
I have removed reference to Newtonsoft.Json 8.0. Other libraries of MtApi are using version 12.0.
