### ISSUE TITLE
Loading MtApi expert fails

### ISSUE THREAD

**Issue by saleyn** [vdemydiuk/mtapi#19]
Installed MtApi to MT4's "MQL4\experts" folder, and MTConnector.dll to "MQL4\Libraries" folder, and added that to user's environment PATH.

When dropping MtApi on a chart getting this:
```
2016.09.30 00:29:12.208	Expert MtApi NZDCAD,H1: removed
2016.09.30 00:29:12.207	MtApi NZDCAD,H1: uninit reason 8
2016.09.30 00:29:12.207	MtApi NZDCAD,H1: not initialized
2016.09.30 00:29:12.207	Unhandled exception 0xE0434352
2016.09.30 00:29:12.169	MtApi NZDCAD,H1 inputs: Port=8222; 
```
Any help on how to troubleshoot it? Does it fail to find the MTConnector.dll? If so, what should be its location?

**Comment by vdemydiuk** [comment]
Hello Serge.
You need to build two libraries for working MT side (as server):
- MTConnector.dll. I am placing it to windows system folder, but it can be placed also to any part which is definded in environment PATH. As I remember the folder "MQL4\Libraries" also has to work.
- MtApiService.dll. This library must be placed and registered in GAC (Global Assembly Cache).

If you build installer MtApiInstaller and run it on your PC it will automaticaly install all needed libraries into pre-defined folders.

**Comment by saleyn** [comment]
Yes, it turned out to the a GAC registration issue. I ended up registering the assembly with GAC by hand:
```
gacutil -i MtApiService.dll
```
The reason I didn't use the installer was was for some reason the installer projects in the solution are marked incompatible, and I don't really like depending too much on MS-specific components and installers outside of .NET core framework:
![image](https://cloud.githubusercontent.com/assets/272543/19080584/828b0f78-8a25-11e6-9b40-e06315419e50.png)

Is there a way to avoid having to register `MtApiService.dll` with GAC all together?

**Comment by vdemydiuk** [comment]
MtApiService.dll is using by library MTConnector.dll.
So it must be visible for MetaTrader, because MTConnector is working in context of the terminal. You can try to put MtApiService.dll into folder with terminal.exe (installed folder of MetaTrader).

Regarding to projects of installers: you need to install WIX Tools to use them (http://wixtoolset.org/).

**Comment by saleyn** [comment]
Thanks. Installation of WIX Tools did solve the remaining issues.  It would make sense that you'd include a reference to this in the 'How to build solution' of README.

**Comment by vdemydiuk** [comment]
Yes, you are right. I have added comment about WIX Tools into readme.
