### ISSUE TITLE
Working with multiple symbols

### ISSUE THREAD

**Issue by saleyn** [vdemydiuk/mtapi#20]
Is it possible to have `MtApi` work with multiple symbols without having to drop the EA on each individual chart?

**Comment by vdemydiuk** [comment]
Unfortunately, I have not found good legitimate way to get updates of quotes from terminal without connections to every chart with symbol is needed. But I am still investigating posibility to get quotes without charts.

**Comment by Exellion** [comment]
You can get market info for all symbols, which added to Market watch. So, you can call method MarketInfo in timer function (with period 100 milliseconds for example), and get ask, bid and time of last quote (or each another info, that represents in MarketInfo method)
