### ISSUE TITLE
Incorrect value of indicator iBullsPower

### ISSUE THREAD

**Issue by vdemydiuk** [vdemydiuk/mtapi#201]
Indicator iBullsPower returns incorrect values.

**Comment by dd-ctss** [comment]
This bug is because in the MtApi5.mq5 expert file on line 4197 it incorrectly refers to iBearsPower instead of iBullsPower.

**Comment by vdemydiuk** [comment]
@dd-ctss yes, you are right. I already fixed it. Thank you for help. :)

**Comment by vdemydiuk** [comment]
I will merge it to master soon.
