### ISSUE TITLE
How to integrate this with python?

### ISSUE THREAD

**Issue by eabase** [vdemydiuk/mtapi#207]
Hi, 
This look like a promising solution. 
I would like to integrate this API using Python (or whatever), however, I don't see any information of how the interface works?

I mean:
1. What is the output and expected input and where is the API documentation if any?
2. Is it using windows socket, IP ports, JSON files or something else?

It would be great to have a clear example of:

- (a) How to retrieve and get live ticks from your MT4/5 terminal into a python.
- (b) How to get H1 candles into a python data frame.

**Comment by ackem** [comment]
https://www.mql5.com/en/docs/integration/python_metatrader5

**Comment by eabase** [comment]
@ackem 

Well, yeah, I know about that, but I'm into OSS, which is why I am asking about this. In addition it need to to work with MT4.

**Comment by eabase** [comment]
I see there was a PR #210, to add a MT5 Python example. This would have been great (and probably the smae for MT4), but the PR was closed without any reason. 

@KptKuck
Why did you close that PR?

**Comment by KptKuck** [comment]
> 
> 
> I see there was a PR #210, to add a MT5 Python example. This would have been great (and probably the same for MT4), but the PR was closed without any reason.
> 
> @KptKuck
> Why did you close that PR?

I'm opening a new one, but I still have problems because in the PR commits are not supposed to be in.

Give me time, I'm not a git expert yet

**Comment by KptKuck** [comment]
now ive done
PR https://github.com/vdemydiuk/mtapi/pull/214

**Comment by eabase** [comment]
@KptKuck 
Hi Christian, 
I see that the demo script is [importing](https://github.com/KptKuck/mtapi/blob/06516d1d46f9039212c0ec06536a0f7051eca63a/Examples/Python/Python_to_MT5/main.py#L8) **`MtApi5`**. 

```python
import MtApi5 as mt5
```
Is that the native MT5 python API package from MQ or something else? 

If it is, I can't use it, since I'm using MT4. How can we use MT4 with python here?  
(Should be straight forward since we have a port to talk to... ??)

**Comment by eabase** [comment]
I've now created a working MT4 python script to catch all candle data. I'll post a PR shortly (few days).

**Comment by eabase** [comment]
* Just posted PR in #227 
* Added my own repo ([mt4pycon](https://github.com/eabase/mt4pycon)) for maintaining the **`con3mtapi.py`**.
* Need help with live streaming of ticks...
