### ISSUE TITLE
Send message to Experts tab

### ISSUE THREAD

**Issue by arteny** [vdemydiuk/mtapi#21]
Is it possible to send message to the Experts tab of Tools window of MT?

**Comment by vdemydiuk** [comment]
At this moment MtApi has only MQL functionality. But I think it is not big problem to add functionality for sending messages to windows of MetaTrader. If it is needed I will investigate. What type of window message do you need?

**Comment by arteny** [comment]
@vdemydiuk standard messages from experts:
!(https://s.mail.ru/7MTx/FqewxSKFE)

**Comment by vdemydiuk** [comment]
What type of windows messages you want to send to the expert tab window?

**Comment by arteny** [comment]
@vdemydiuk Just a wrapper for Print function of MQL5

**Comment by vdemydiuk** [comment]
I had some misunderstanding with you from first your message. I thought about windows messages. 
As I understand now you need common function Print (https://www.mql5.com/en/docs/common/print).
Am I right?

**Comment by arteny** [comment]
@vdemydiuk Yes, it is
