### ISSUE TITLE
Manually copying of MtApi5.ex5 into expert folder dissappears

### ISSUE THREAD

**Issue by eabase** [vdemydiuk/mtapi#219]
Hi, 
I tried to manually copy the `MtApi5.ex5` file into the `..\MQL4\Experts` folder. And as soon as I refresh the datafolder from within MT4, it disappears.  I tried renaming the file etc. No go. What's going on?

**Comment by vdemydiuk** [comment]
Why are you using MtApi5.ex5 for MT4? It works with MT5.
You should use MtApi.ex4.

**Comment by eabase** [comment]
> Why are you using MtApi5.ex5 for MT4? It works with MT5.

Yes, even better reason why it should not randomly disappear. I wish MQ wouldn't be such a  black hole and tell us what their app is doing. 

> You should use MtApi.ex4.

Yes, I tried that too, and under some (unknown) circumstances it happened to that one too.

But I just wanted to report back, that this actually happens.
