### ISSUE TITLE
Why we cant use in Tester in MT4

### ISSUE THREAD

**Issue by keyvanarasteh** [vdemydiuk/mtapi#22]
it's hanging in "Waiting on remote client..."

as screenshot below : 

![image](https://cloud.githubusercontent.com/assets/16303698/19552620/6d318b8a-96bd-11e6-8756-d49a896bf9be.png)

**Comment by vdemydiuk** [comment]
Yes, you are right. MtApi Expert is waiting on incoming connection by MtApi Client in tester mode.
After they will be connected MtApi Expert will continue to work.

**Comment by vdemydiuk** [comment]
I have found problem with in version 1.0.30. It will be fixed in 1.0.31.
