### ISSUE TITLE
Please provide separate download for DLL build artifacts

### ISSUE THREAD

**Issue by eabase** [vdemydiuk/mtapi#220]
Please provide separate downloads for the built DLL's. Right now they're mysteriously packaged into the installer, and not easily extracted separately, which makes it hard to test if what you packaged is the same that the code is building, while allowing other tests and moving of files when using multiple and portable terminals.

**Comment by eabase** [comment]
No need for separate download, just fix the .gitignore.

**Comment by vdemydiuk** [comment]
I rejected PR with  .gitignore.
I will provide zip with DLLs in releases.
