### ISSUE TITLE
Not able to use MtApi EA with investor password

### ISSUE THREAD

**Issue by eabase** [vdemydiuk/mtapi#223]
**Problem:**

The EA get unhappy if you use a non-tradable account for MT login credentials. 
This presumably prevent further use of the EA & API. 

**Expected**
We should be able to do all normal operations , apart opening a *trade*, even when using _investor_ credentials.  `:)`

**Comment by eabase** [comment]
@vdemydiuk 
Is there a way you can modify the EA to allow using it also with an investor password?

**Comment by eabase** [comment]
This is probably related to #78.

**Comment by eabase** [comment]
Easy fix: 
```cpp
    if (IsTradeAllowed() == FALSE) {
        MessageBox("Trading is Disabled.", "MT4 API EA", MB_OK);
        //isCrashed = TRUE;
        //return (1);
    }
```

**Comment by vdemydiuk** [comment]
@eabase  Yes, you are right.
This checking prevents using MtApi with non-tradable accounts. It was added on the begining of the project and it is not actual for now.
I will remove code that stops experts if trade is not allowed (for both versions, MT4 and MT5).
User always can check this mode in runtime by calling function:
IsTradeAllowed() - MT4
TerminalInfoInteger(property TERMINAL_TRADE_ALLOWED) - MT5.
