### ISSUE TITLE
Add missing ErrorCodes for MT4

### ISSUE THREAD

**Issue by eabase** [vdemydiuk/mtapi#224]
Not sure, but it seem that many error codes are missing from the MT4 API. 
That does make sense as they're not even documented on the MQ site, but used in distributed files. 

Please see: 
* https://github.com/iamideas/Mql-for-MT4/blob/master/stderror.h

**Comment by KptKuck** [comment]
This is the official list.
https://docs.mql4.com/constants/errorswarnings/errorcodes
Which code is missing ?

**Comment by eabase** [comment]
Hmm. Pretty sure I could not find find some of them there, a week ago. 
So just poor google-fu then.
