### ISSUE TITLE
What limits the number of candles returned by CopyRates()? 

### ISSUE THREAD

**Issue by eabase** [vdemydiuk/mtapi#225]
I'm not sure this is an issue, but is seem like the `CopyRates` function is only able to receive 3086 candles.
Since my terminal `MaxBars` are set to *512,000*, I believe it is a broker issue.

```
  INFO: CopyRates: Symbol    :  EURUSD
  INFO: CopyRates: TimeFrame :  M5
  INFO: CopyRates: Requested :  10000 candles
  INFO: CopyRates: Received  :  3086 candles
  INFO: CopyRates: ErrorCode :  0
```
This is approximately `(3086 candles * (1 hr/12 candles) * (1 day/24 hr)` = 10 days of trading data. This also coincide with the chart scroll back. 

Is there a way to see a priori, how much data is available on the chart, given a TF?

**Comment by KptKuck** [comment]
https://docs.mql4.com/series/copyrates

**Comment by eabase** [comment]
@KptKuck 
1. First of all, I've **obviously** already looked there, since I am getting the data already, just not the amount I expected. 
2. AFAICR @vdemydiuk mentioned  in the telegram channel, he implemented the method to get a `List<MqlRates>` for both MT4 and MT5 version, which is not of the format you linked to. 
3. I'll be the first to admit I don't understand why the MQ docs state to return `<int>` whereas mtapi choose to deliver a list (as above)?  

This works in Py3:
```python
rA  = client.CopyRates(SYM, TF, startPos, count)        # MT4:  List<MqlRates>
len(rA)
# 3112
```
Look like I a might be able to use `iBars()`...
```python
cc=client.iBars('EURUSD',5)
# 3112
```

Still no answer if this is a broker, buffer issue, or an API issue? (What is setting the limit?)

**Comment by KptKuck** [comment]
What is your setting for MAXBARS ?
Try higher values

**Comment by KptKuck** [comment]
Try a restart from MT4 after setting MAX_BARS

**Comment by eabase** [comment]
This is not a `MAX_BARS` issue, AFAIK.  
Most likely a broker issue. (Scrolling back the charts give the same limits.)

**Comment by KptKuck** [comment]
@eabase ok

**Comment by eabase** [comment]
I think I just have a really shitty broker. So I'll close this for now.

**Comment by KptKuck** [comment]
> 
> 
> I think I just have a really shitty broker. So I'll close this for now.

MT5 Python Example
Count is at 250000.
no problem
![grafik](https://user-images.githubusercontent.com/17534012/100536689-87968e80-3222-11eb-9785-0dcb0bda7bc5.png)

**Comment by eabase** [comment]
@KptKuck 
Can you show how you got the events to work for you?
I'm not able to get the `ConnectionStateChanged` working properly.

**Comment by KptKuck** [comment]
@eabase 
![grafik](https://user-images.githubusercontent.com/17534012/100870597-2cbd9b00-349f-11eb-95ee-053b646afbf6.png)

**Comment by eabase** [comment]
Great! My first attempt didn't work for some reason.
