### ISSUE TITLE
[MT4] Implement lock ticks for quote events (Backtesting)

### ISSUE THREAD

**Issue by vdemydiuk** [vdemydiuk/mtapi#226]
Current implementation has lock ticks for candle event only.
Need to add locking ticks for every quote events (like MT5 version):
enum LockTickType
{
   NO_LOCK,
   LOCK_EVERY_TICK,
   LOCK_EVERY_CANDLE
};

**Comment by eabase** [comment]
I just googled for this, but didn't find anything.
What are these *lock ticks* used for?

**Comment by eabase** [comment]
Hmm, seem related to:

* https://github.com/vdemydiuk/mtapi/blob/f01ec01a5f3f81d64d0ba2c7252734d54e30343a/MtApi/MtEventTypes.cs#L1-L8

Maybe this is what I am looking for. The missing Tick events?

**Comment by vdemydiuk** [comment]
@eabase I added small description in #237.
