### ISSUE TITLE
MqlRates definition

### ISSUE THREAD

**Issue by arteny** [vdemydiuk/mtapi#23]
At least in MtApi5 it is bad defined.
1. It is necessary empty public constuctor.
2. Please change order of properties in class as in MQL5:
   datetime time;         // время начала периода 
   double   open;         // цена открытия 
   double   high;         // наивысшая цена за период 
   double   low;          // наименьшая цена за период 
   double   close;        // цена закрытия 
   long     tick_volume;  // тиковый объем 
   int      spread;       // спред 
   long     real_volume;  // биржевой объем 
3. Existing construcor (where order is correct) - need add default values from tick_volume.

Puropose: for deserialization.
I can prepare pull request if needed.

**Comment by vdemydiuk** [comment]
You are right. 
I will fix it. 
Thank you for this issue.

**Comment by vdemydiuk** [comment]
Fixed!
