### ISSUE TITLE
[MT4] Broken build of MTConnector.dll

### ISSUE THREAD

**Issue by vdemydiuk** [vdemydiuk/mtapi#230]
Commit 1a1b0cd822352bf3d32df2c977d1cb601202179c has broken build of MTConnector project.

![image](https://user-images.githubusercontent.com/5229395/99114735-f4424400-25f9-11eb-9109-1b2a7a15f64a.png)

**Comment by eabase** [comment]
@vdemydiuk 
I guess you fixed it now. (So maybe lets start closing some older and fixed issues/questions here?)
