### ISSUE TITLE
[enhancement] Make unified installer for both MT4 and MT5

### ISSUE THREAD

**Issue by eabase** [vdemydiuk/mtapi#234]
Because the 32-bit version of MT5, is now officially obsolete, we can make a unified installer that would install the DLL's for both MT4 and MT5.

* See: https://github.com/vdemydiuk/mtapi/issues/222#issuecomment-727230872

**Comment by vdemydiuk** [comment]
I am not sure that it will be good idea to make unified installer. 
I see several issues to do it:
1) MtApi (MT4 and MtApi5 (MT5) are different projects with different versions. Installer is using version of concrete project - MtApi or MtApi5. If new release one of them will be done then it will have new version but another still will have old version. This can be confusing for users.
2) MtApi (MT4) is x86 project. MetaTrader 4 is still 32-bit. Unified installer must install libraries with both configuration.
3) MetaTrader 4 is old application and I think it will die soon. And related projects will be deleted from solution (MtApi, MTConnector, MtApiInstaller).

Using different installers of MtApi and MtApi5 also allows to use different versions of MTApiService.dll independently. Several versions of MTApiService can be installed into GAC.

**Comment by eabase** [comment]
I see, cool and thanks for full explanation.
