### ISSUE TITLE
Problem with OrderSendAsync() in MtApi5

### ISSUE THREAD

**Issue by ackem** [vdemydiuk/mtapi#251]
Hi Vyacheslav.

Please help me.

In this simple code:
```
                MtApi5Client _mt = new MtApi5Client();
		MqlTradeRequest request = new MqlTradeRequest();
                MqlTradeResult result = null;
                request.Action = ENUM_TRADE_REQUEST_ACTIONS.TRADE_ACTION_PENDING;
                request.Symbol = symbol;
                request.Volume = volume;
                request.Price = price;
                request.Type = ENUM_ORDER_TYPE.ORDER_TYPE_BUY_LIMIT;
                request.Type_filling = ENUM_ORDER_TYPE_FILLING.ORDER_FILLING_RETURN;
                request.Type_time = ENUM_ORDER_TYPE_TIME.ORDER_TIME_DAY;
                bool boolResult = _mt.OrderSendAsync(request, out result);
```

Method OrderSendAsync() throws exception:
```
MtApi5.ExecutionException: Unknown request type
   at MtApi5.MtApi5Client.SendRequest[T](RequestBase request)
   at MtApi5.MtApi5Client.OrderSendAsync(MqlTradeRequest request, MqlTradeResult& result)
   at testing_MtApi5.Program.Main(String[] args) in C:\CSharpProjects5\testing_MtApi5\testing_MtApi5\Program.cs:line 65
```

**But the same code with OrderSend() works ok.**

**Comment by ghhv** [comment]
Hi Ackem,
What is `_mt`?  
This should work... 
` MtApi5Client _mt = new MtApi5Client();
  bool boolResult = _mt.OrderSendAsync(request, out result);`

**Comment by ackem** [comment]
> This should work...
> ` MtApi5Client _mt = new MtApi5Client(); bool boolResult = _mt.OrderSendAsync(request, out result);`

Yes, I do so.
Don't work, Bro.

**Comment by ghhv** [comment]
did  you add references to that project? and mt5api?

**Comment by ackem** [comment]
> But the same code with OrderSend() works ok. 
!!!

**Comment by ghhv** [comment]
yes, but you should be awaiting an async.. I don't have MT5 to test, but in the MT4 API, you'd do it like this:
`await Execute(() => _mtapi.GetOrder(blah, blah));`

**Comment by vdemydiuk** [comment]
@ackem
In my opinion you haven't update MtApi5.ex5 in your Terminal's data folder for Expert Advisors (../MQL5/Experts).
Please check it.

**Comment by ackem** [comment]
@vdemydiuk 
Works!
You're magician!)
Thank you, Bro)
