### ISSUE TITLE
Backtesting MT4

### ISSUE THREAD

**Issue by sej2016** [vdemydiuk/mtapi#28]
Hi,

It is a way to use indicators in Backtesting mode, i have always a exception if i try to use it.
I have also a problem with OrderSend in Backtesting mode, i get always a exception with a concurency mode error.

Thanks in advance
Regards

**Comment by vdemydiuk** [comment]
Backtesting was broken in version 1.0.30. Related issue #26.
I have fixed this problem and will make release ASAP.

**Comment by vdemydiuk** [comment]
How to use backtesting (in MetaTrader 4):

How to use backtesting:
- Open Strategy tester (Ctrl+R).
- Select MtApi.ex4. You can set port for connection in Expert properties.
- Set all necessary properties for backtesting (Period, Symbol, dates and other).
- Press Start. MtApi.ex4 will wait on incoming connection from client side.
- Start client side and connect on defined port. MtApi.ex4 will resume backtesting.

**Comment by sej2016** [comment]
Many thanks
Your last release is working fine
Regards
