### ISSUE TITLE
MtApi bad logging

### ISSUE THREAD

**Issue by arteny** [vdemydiuk/mtapi#29]
When I started my application I got
	log4net:ERROR RollingFileAppender: INTERNAL ERROR. Append is False but OutputFile [C:\Users\Alexey\AppData\Local\Temp\MtApi5Client\Logs\2016-04-11--23-46-42.txt] already exists.	

I am not sure what is reason, but looks like there is a initialization of logging from MtApi5.dll itself. I think it is not good way to initialize logging from library and it should be initialized from client application (for instance add appropriate API call) and library itself should only add messages logging calls (they will find log instance correctly).

I am using such configuration in my client (looks like same logging framework is used):
			Log.Logger = new LoggerConfiguration()
			.MinimumLevel.Debug()
			.WriteTo.Trace()
			.CreateLogger();

**Comment by vdemydiuk** [comment]
I am trying to reproduce your issue.
Have you started several instances of the application with MtApi client?

As I see from your log configuration you are using Serilog .NET logging (https://github.com/serilog/serilog).
I am using log4net logging framework. So I am not sure that we will have any conflicts with loggers.

**Comment by arteny** [comment]
Yes, I am using Serilog/
As for several instances - no, I am using only one, and this error is not stable reproducable, just sometimes I could see such errors.

**Comment by vdemydiuk** [comment]
Please test version 1.0.11 and let me know if you still have this problem.

I have reopened this issue for deep investigation.

**Comment by arteny** [comment]
Didn't find it again. Looks like fixed.

**Comment by vdemydiuk** [comment]
Ok. I close this issue. If it happens again I will reopen this isse.
