### ISSUE TITLE
SymbolInfoDouble

### ISSUE THREAD

**Issue by srodelo** [vdemydiuk/mtapi#31]
I could not find support for SymbolInfoDouble. Are there plans to develop? Can I develop and make pull request?

**Comment by vdemydiuk** [comment]
I will implement it soon.
But if you want you can developed it and I will add it to master branch.

**Comment by vdemydiuk** [comment]
I will add all functions of Market Info (https://docs.mql4.com/marketinformation) in the next version MtApi (MT4) 1.0.32.
