### ISSUE TITLE
there is no drawing methods implemented

### ISSUE THREAD

**Issue by keyvanarasteh** [vdemydiuk/mtapi#32]
hi guys.

i cant draw any object on charts with Api.

Arrows, Lines, Fibos, HorizantalLines, Trends, VerticalLines, Image, ....

is there any method to do that ?

thanks.

**Comment by vdemydiuk** [comment]
Hi.
Do you mean Object Functions (https://docs.mql4.com/objects) ?

Object Functions are not implemented in MtApi. 
Do you need this functions in C# client?

**Comment by keyvanarasteh** [comment]
yes i need to show calculation results on chart.

you dont use ??

it's very important to me :-(

**Comment by vdemydiuk** [comment]
I can implement object functions but I see one problem of implementation: if you will have several charts connected with MtApi.ex4 on one port (default 8222), you will determine on which chart the object will be drawn. 
So in this case only single chart connection will work correct. Is it good for you ?

**Comment by vdemydiuk** [comment]
I think I can make object functions with Symbol parameter which will determine the chart to draw objects.

**Comment by keyvanarasteh** [comment]
Exactly we can use Symbol for drawing object.

even you can implement OpenChart Methods too. 

to Open Charts Detected as tradeble by our algorithms.

many of people like to trade on MetaTrader like me but calculations is easier to do in c# then transfer final results to mt4 charts.  ;-)

**Comment by keyvanarasteh** [comment]
i'm implementing that :-D

**Comment by vdemydiuk** [comment]
Ok. I will work on it after release 1.0.32. I think I will implement it to end of this month.
