### ISSUE TITLE
Backtesting MT4 fails (1.0.32)

### ISSUE THREAD

**Issue by chadoe** [vdemydiuk/mtapi#37]
An exception is thrown when trying to call an apiclient function from the QuoteUpdated event when backtesting in MT4:

```
An exception of type 'MtApi.MtConnectionException' occurred in MtApi.dll but was not handled in user code

Additional information: Service connection failed! This operation would deadlock because the reply cannot be received until the current Message completes processing. If you want to allow out-of-order message processing, specify ConcurrencyMode of Reentrant or Multiple on CallbackBehaviorAttribute.
```
The code below for a test console app fails on call to `iBars` for instance:
```c#
using MtApi;
using System;

namespace MT4ClientConsole
{
   class Program
   {
      static void Main(string[] args)
      {
         MtApiClient client = new MtApiClient();
         client.QuoteUpdated += Client_QuoteUpdated;
         client.BeginConnect("127.0.0.1", 8222);
         Console.ReadKey();
      }

      private static void Client_QuoteUpdated(object sender, string symbol, double bid, double ask)
      {
         var bars = ((MtApiClient)sender).iBars(symbol, ChartPeriod.PERIOD_M5);
         Console.WriteLine("Bars: " + bars);
      }
   }
}
```

**Comment by vdemydiuk** [comment]
You have called in function iBars in the same thread of callback QuoteUpdated. Backtesting mode has synchronic events QuoteUpdated to allow debug on quote (MetaTrader will be freezed on tick will). So you will have deadlock in backtesting (and will not in normal mode).
You should call iBars and other functions of MtApiClient in async methods. For example:

private static void Client_QuoteUpdated(object sender, string symbol, double bid, double ask)
{
    Task.Factory.StartNew(() =>
    {
        var bars = ((MtApiClient)sender).iBars(symbol, ChartPeriod.PERIOD_M5);
        Console.WriteLine("Bars: " + bars);
    });
}

**Comment by vdemydiuk** [comment]
I will fix this problem in MtApi by using ConcurrencyMode = ConcurrencyMode.Multiple. 
You will not need async methods and tasks to call mtapi functions during events.
