### ISSUE TITLE
Memory usage keeps growing (1.0.32)

### ISSUE THREAD

**Issue by chadoe** [vdemydiuk/mtapi#38]
Memory usage of MetaTrader 4 grows rapidly when using MtApi.

To reproduce start a backtest in MT4 with the strategy tester (one day is enough), run app below (which does nothing but connect), watch the memory usage of the MetaTrader process in the task manager quickly grow to several GB's.

```C#
using MtApi;
using System;

namespace MT4ClientConsole
{
   class Program
   {
      static void Main(string[] args)
      {
         MtApiClient client = new MtApiClient();
         client.BeginConnect("127.0.0.1", 8222);
         Console.ReadKey();
      }
   }
}
```

**Comment by vdemydiuk** [comment]
Yes, I aslo found this problem in last versions of MtApi (MT4 and MT5).
I will try to fix it in version 1.0.33

**Comment by chadoe** [comment]
Thank you, really interesting project you have here.

**Comment by vdemydiuk** [comment]
I have found memory leaks in log4net libraries (logging).
