### ISSUE TITLE
MTApi.mq4  compile problem

### ISSUE THREAD

**Issue by adblueGmbH** [vdemydiuk/mtapi#46]
Hello, I have tried to compile the MTApi.mq4 in the MetaEditor as far as it works but If run this version and in TestApiClinet and click on symbolTotal the ea crached ..
2017.02.15 15:55:31.261 Access violation read to 0x0BFFFFF8 in  xxx/Terminal\9099EE68906C5004CBE96894295C3478\MQL4\Experts\MtApi.ex4'

**Comment by vdemydiuk** [comment]
Hi,
please contact me via skype, I will try find the problem and to help you online.

**Comment by vdemydiuk** [comment]
@adblueGmbH 
I think you did not installed MtApiService.dll and MTConnector.dll correctly. Can you check that file MTConnector available in folder c:\Windows\SysWOW64\ and MTApiService.dll is present in GAC folder
(by default, c:\Windows\Microsoft.NET\assembly\GAC_MSIL\)

**Comment by vdemydiuk** [comment]
I am closing this issue because I have not received any answer long time and there are no any new feedbacks about this issue.
