### ISSUE TITLE
Release of MtApi_Setup.exe

### ISSUE THREAD

**Issue by puresoul** [vdemydiuk/mtapi#49]
Hi,

the WIX installator is missing MTConnector.dll, so whole release is broken. Version before has same fault.

**Comment by vdemydiuk** [comment]
Are you trying to build configuration Release - x86 ?

**Comment by puresoul** [comment]
nope, I was trying to install release.

here

https://github.com/vdemydiuk/mtapi/releases/download/MT4-v1.0.34/MtApi_Setup.exe

and here

https://github.com/vdemydiuk/mtapi/releases/download/MT4-v1.0.33/MtApi_Setup.exe

**Comment by vdemydiuk** [comment]
MTConnector is installing into window system folder, by default for Windows x64:
c:\Windows\SysWOW64\
Can you check this location on your PC after installed mtapi?

**Comment by puresoul** [comment]
ok, I found that library and now its working. Thanks

**Comment by vdemydiuk** [comment]
Great. I am closing this issue.
