### ISSUE TITLE
Color representation

### ISSUE THREAD

**Issue by Tr4Dr** [vdemydiuk/mtapi#5]
MQL uses different color representation than C# System.Drawing.Color.

MQL4 color ( https://docs.mql4.com/basis/types/integer/color ):
**0x00BBGGRR**
**00**: ignored values
**BB**: Blue component
**GG**: Green component
**RR**: Red component

System.Drawing.Color ( https://msdn.microsoft.com/en-us/library/system.drawing.color%28v=vs.110%29.aspx ):
**0xAARRGGBB**
**AA**: Alpha component
**BB**: Blue component
**GG**: Green component
**RR**: Red component

A possible fix in **`MtApiColorConverter.cs`**:

```C#
using System.Drawing;

namespace MtApi
{
    class MtApiColorConverter
    {
        public static Color ConvertFromMtColor(int mqlColor)
        {
            return Color.FromArgb((byte)(mqlColor), (byte)(mqlColor >> 8), (byte)(mqlColor >> 16));
        }

        public static int ConvertToMtColor(Color color)
        {
            return color == Color.Empty ? 0xffffff : (Color.FromArgb(color.B, color.G, color.R).ToArgb() & 0xffffff);
        }
    }
}
```

**Comment by vdemydiuk** [comment]
Hello Tr4Dr.
Great information. Thank you.
I will upate color converter with this code.
