### ISSUE TITLE
Loading MtApi expert fails (MT4)

### ISSUE THREAD

**Issue by AqpA** [vdemydiuk/mtapi#50]
Hello,
Thanks for your api everything is working. But I have a problem; 
If I download MtApi_Setup.exe and install it, MTConnector.dll size 494 KB ( Working )
If I built MTConnector project, MTConnector.dll size 485 KB and notworking (MetaTerminal MtApi.ex4 not load file there is no smiling face in the upper right corner)

Thanks.

**Comment by vdemydiuk** [comment]
Where are you placing library MTConnector.dll in file system? It must be places in windows system folder or in folder near terminal.exe.

**Comment by AqpA** [comment]
I trayed syswow64 and meta setup folder (near terminal.exe)

**Comment by vdemydiuk** [comment]
Have you installed MTApiService.dll into GAC ?

**Comment by AqpA** [comment]
Yes under the GAC directory.
Download MtApi_Setup.exe and install it, MTConnector.dll size 494 KB ( Working ) but built MTConnector project, MTConnector.dll size 485 KB (notworking), if I change 485 KB file whit 494 KB everything is work.

**Comment by vdemydiuk** [comment]
Please contact with me via skype. I will try to check your problem online.

**Comment by Exellion** [comment]
Try to build MTConnector in Release mode.

**Comment by vdemydiuk** [comment]
@Exellion yes, you are right, Release mode can help.
@AqpA please try to build MTConnection in release mode and let me know if it is working.

**Comment by vdemydiuk** [comment]
I am closing this issue because I have not received any answer long time and there are no any new feedbacks about this issue.
