### ISSUE TITLE
Connecting localhost 8222

### ISSUE THREAD

**Issue by kadirmustafa** [vdemydiuk/mtapi#51]
HEllo

in metatrader when i run MtApi it works successfully but i could not connect to localhost 8222 from TestApiClientUI. i am trying to connect over telnet but it also fails

in MetaTrader Experts Log;
2017.03.06 22:15:48.632	MtApi GBPJPY`,H1 inputs: Port=8222; 
2017.03.06 22:15:47.320	Expert MtApi GBPJPY`,H1: loaded successfully

**Comment by vdemydiuk** [comment]
Please try function BeginConnect without Host for local connection or leave empty textbox Host. It must work.
