### ISSUE TITLE
Could you please add support for "Chart Operations" command?

### ISSUE THREAD

**Issue by Mark-Joy** [vdemydiuk/mtapi#53]
Hello, could you please add support for "Chart Operations" command?
https://docs.mql4.com/chart_operations

**Comment by vdemydiuk** [comment]
Hi.
I will investigate functions of Chart Operation and will start to implement soon. (I think during the next month).

**Comment by vdemydiuk** [comment]
I still working on this issue. I hope I will complete it in Aug.
