### ISSUE TITLE
How to login my MT4 account

### ISSUE THREAD

**Issue by AndrewDerain** [vdemydiuk/mtapi#56]
Hello vdemydiuk, I'm new to this project. Now I know how to connect to the MT4 server(though I never succeed!) But How can I login my account after I connect to MT4 server. Thank you!

**Comment by vdemydiuk** [comment]
Hi!
You don't need in login account. MtApi is using current account that is login in MT4.
MtApi does not provide any functions to change or login account.

**Comment by vdemydiuk** [comment]
I have implemented function ChangeAccount. Maybe it will help you.

public bool ChangeAccount(string login, string password, string host);
