### ISSUE TITLE
OnTick

### ISSUE THREAD

**Issue by alexssource** [vdemydiuk/mtapi#63]
Hi, Vyacheslav!
Sorry for my dummy question,
but is there are available proxy for OnTick(Tick) function for MT4?
In the source I've found the updateQuote method, but I'm not sure is it the same.

**Comment by vdemydiuk** [comment]
Hi!
Yes, QuoteUpdate and QuoteUpdated events are the same as OnTick in MQL.

**Comment by sn50** [comment]
This is a perfect FAQ question. Did you consider creating one?

**Comment by vdemydiuk** [comment]
Yes, I think this is very good idea to create FAQ for the project. I will do it when I will have more free time.
