### ISSUE TITLE
Cannot call 'MTConnector.dll::initExpert', 'MTConnector.dll' is not loaded

### ISSUE THREAD

**Issue by cnbabycrazy** [vdemydiuk/mtapi#65]
vps：https://www.alibabacloud.com/product/ecs?spm=a3c0i.7919406.692950.dznavproductsa1.10de5371Ypdw5V#overview

system：Windows Server  2008 Standard (X86 based PC), IE 09.00, RDP, UAC, 1 x Intel Xeon  E5-2680 v3 @ 2.50GHz, RAM: 387 / 1022 Mb, HDD: 30684 / 40957 Mb, GMT+08:00

MetaEditor Err Log：
0	00:47:26.292	Expert MtApi EURUSD.,H1: loaded successfully
0	00:47:26.292	MtApi EURUSD.,H1 inputs: Port=8222; BacktestingLockTicks=false; 
3	00:47:29.199	Cannot load 'C:\Users\Administrator\AppData\Roaming\MetaQuotes\Terminal\3A583B7241221ECE36936302092EE39E\MQL4\Libraries\MTConnector.dll' [126]
1	00:47:29.214	Cannot call 'MTConnector.dll::initExpert', 'MTConnector.dll' is not loaded
1	00:47:29.214	MtApi EURUSD.,H1: unresolved import function call
3	00:47:29.214	MtApi EURUSD.,H1: not initialized
0	00:47:29.214	MtApi EURUSD.,H1: uninit reason 8
0	00:47:29.214	Expert MtApi EURUSD.,H1: removed

MT4 Err Log：
2	00:54:38.217	Expert MtApi EURUSD.,H1: loaded successfully
2	00:54:39.576	Expert MtApi EURUSD.,H1: removed

Setup Info
![20170920005839](https://user-images.githubusercontent.com/7571957/30604953-f170e7b8-9d9e-11e7-8a6f-b1f22457bd48.png)

**Comment by cnbabycrazy** [comment]
Some of these pseudo-VPS offerings don't provide a full Windows environment, and some DLL calls and dependencies will not work.

**Comment by vdemydiuk** [comment]
Please contact with me via skype: dem_dw.
I will try to help you online.

**Comment by cnbabycrazy** [comment]
thanks, I solved this issue. Lacking those msvcp140d.dll vcruntime140d.dll ucrtbased.dll Wlanapi.dll files in server caused this issue. I'll add your skype later, there may have other issues.

**Comment by parinazk** [comment]
I have same error on Windows Server 2012 x64, how can I fix this error?

**Comment by vdemydiuk** [comment]
Have you tried to install related vcredist?

**Comment by parinazk** [comment]
Yes,install Microsoft Visual C++ 2010 Redistributable and Microsoft Visual C++ 2015 Redistributable.

![Untitled](https://user-images.githubusercontent.com/6314380/61153197-c75eb800-a4ff-11e9-8f7a-61079bfa9b51.png)

**Comment by vdemydiuk** [comment]
Please check missed libraries needed for MTConnector.dll with utility dependency walker.

**Comment by parinazk** [comment]
I checked missed libraries by dependency walker,but i can't find missed libraries in internet.

![Untitled](https://user-images.githubusercontent.com/6314380/61174845-39e09e00-a5bb-11e9-9933-b449efe2897d.png)
