### ISSUE TITLE
HistoryDealGetDouble

### ISSUE THREAD

**Issue by WP517i** [vdemydiuk/mtapi#72]
Please help!
HistoryDealGetDouble - it's not work.
Here my code:
_mtApiClient.HistoryDealGetDouble(DealTicket, ENUM_DEAL_PROPERTY_DOUBLE.DEAL_PRICE)

ENUM_DEAL_PROPERTY_DOUBLE have exception!
Error of serialization parameter.
Sorry for english!

MT5

**Comment by vdemydiuk** [comment]
Hi!
Yes, you are right. This function has bug with serialization of parameters. Also the same bug is available in similar functions HistoryDealGetInteger, HistoryDealGetString.
I will fix it ASAP (in next version).

**Comment by WP517i** [comment]
Iis there any solution?

**Comment by vdemydiuk** [comment]
Могу собрать бета версию для вас с исправлениями.
Свяжитесь со мной по скайпу или эл. почте.
