### ISSUE TITLE
iBarShift Bad Results

### ISSUE THREAD

**Issue by mhdbzr** [vdemydiuk/mtapi#73]
The `iBarShift` function returns wrong value.
(Maybe `time` parameter casting in `Execute_iBarShift` function is wrong)
.NET Code (in VB) sends request for two different times but gets the same results (25)

    MyCharts(0).SymbolName = "EURUSD"
    MyCharts(0).Timeframe = ENUM_TIMEFRAMES.PERIOD_D1
    Dim Mt4Time = _Client.TimeCurrent()
    Dim Time5 = _Client.iTime(MyCharts(0).SymbolName, MyCharts(0).Timeframe, 5)
    Dim Counts1 As Integer = _Client.iBarShift(MyCharts(0).SymbolName, MyCharts(0).Timeframe, Mt4Time , True)
    Dim Counts2 As Integer = _Client.iBarShift(MyCharts(0).SymbolName, MyCharts(0).Timeframe, Time5 , True)

I've tried to debug MtApi.mq4 with loging `time` and `res` variables in `Execute_iBarShift`:

> 2017.12.05 14:40:56.245	MtApi EURUSD,H1: 1509949440=2017.11.06 06:24 - res:25
> 2017.12.05 14:40:56.247	MtApi EURUSD,H1: OnRequest: RequestType = 9
> 2017.12.05 14:40:56.247	MtApi EURUSD,H1: CreateSuccessResponse: {"ErrorCode" : 0,"Rates" : [{"Close" : 1.18671,"Open" : 1.18557,"MtTime" : 1512345600,"Low" : 1.18283,"High" : 1.18777,"TickVolume" : 41258,"RealVolume" : 0,"Spread" : 0}]}
> 2017.12.05 14:40:56.247	MtApi EURUSD,H1: OnRequest: Response = {"ErrorCode" : 0,"Rates" : [{"Close" : 1.18671,"Open" : 1.18557,"MtTime" : 1512345600,"Low" : 1.18283,"High" : 1.18777,"TickVolume" : 41258,"RealVolume" : 0,"Spread" : 0}]}
> //int time = 1509949440
> //TimeToString(time) = 2017.11.06 06:24

**Comment by vdemydiuk** [comment]
Hello.
I have reproduced you issue and found the problem:
the function "getBooleanValue" has received boolean parameter but it is operating with int value inside. So we have corrupted stack. I will fix it soon.

**Comment by vdemydiuk** [comment]
I have fixed the issue in 1.0.39.
