### ISSUE TITLE
Indiscriminate Logging

### ISSUE THREAD

**Issue by Victoriadd2007** [vdemydiuk/mtapi#76]
Is there any way to not to log everything? My Experts tab on MT4 is full with garbage from Execute Request calls and the log is almost 100Mb large in the first 30 minutes.  Any search on orders (i.e., Orders Total) will fire the log a million times if checked often and/or in many charts.

**Comment by vdemydiuk** [comment]
If you told about logging in console of MetaTrader terminal, yes, I will disable most of unnecessary logging information.

**Comment by vdemydiuk** [comment]
I have disabled unnecessary logging in release mode.
