### ISSUE TITLE
TerminalInfoString doesn't work for MT4

### ISSUE THREAD

**Issue by mpvyard** [vdemydiuk/mtapi#80]
Hi! 

I tried to call the method **TerminalInfoString**, but received an MtExecutionException with MtApiCustomError. Methods **TerminalinfoDouble** and **TerminalinfoInteger** work well. In the test GUI client calling this method is omitted, I added it, but got the same error.

What could be the reason for this error?

**Comment by vdemydiuk** [comment]
Hi.
I will investigate this problem soon.

**Comment by vdemydiuk** [comment]
I have found small bug in mql4 code.
I will commit new fix asap.

**Comment by mpvyard** [comment]
Good news, thanks!

**Comment by vdemydiuk** [comment]
Welcome. :)
