### ISSUE TITLE
OrderSend @ MT5 Connector returns empty MqlTradeResult

### ISSUE THREAD

**Issue by cia76** [vdemydiuk/mtapi#82]
private static readonly MtApi5Client MTApi5Client = new MtApi5Client();

        internal ulong OrderSend(MqlTradeRequest MqlTradeRequest)
        {
            MqlTradeResult result;
            bool state;
            lock (MTApi5Client)
            {
                state = MTApi5Client.OrderSend(MqlTradeRequest, out result);
                // Получаем state == true, в MT5 открывается позиция, но в result возвращается Null
            }
            if (state) // Если заявку поставили
            {
                Logger.Debug($"Заявка отправлена. Номер тикета: {result.Order}");
                return result.Order;
            }

            Logger.Error(result != null ? $"Ошибка OrderSend {result.Retcode}" : "Ошибка OrderSend");
            return 0;
        }

Аналогичная ситуация и в примере кода:
![mtclient](https://user-images.githubusercontent.com/34663130/35606851-080c78a6-0673-11e8-9966-5e0cb9bca355.jpg)

**Comment by vdemydiuk** [comment]
I need time to investigate this problem. If I find related bug I will fix in asap.

**Comment by vdemydiuk** [comment]
I have tried to reproduce the issue but can't. I have got success result after call function OrderSend (see attached my picture).
Please contact with me via Skype (dem_dw). I will try to help you online.

![screenshot 2018-02-09 11 22 38](https://user-images.githubusercontent.com/5229395/36020612-f9fb288c-0d8b-11e8-9967-4fc7f1765575.png)

**Comment by vdemydiuk** [comment]
Colleagues, 
does anybody have the same error with OrderSend? I can't reproduce it.

**Comment by KptKuck** [comment]
no , OrderSend works fine

**Comment by KptKuck** [comment]
[https://i.imgur.com/onDvzEz.png](url)

**Comment by vdemydiuk** [comment]
Yes, you are right. The price and other parameters must be correct to place order. Otherwise a result will be failed.

**Comment by cia76** [comment]
Here is the breakpoint in your test MT5 client:

![image](https://user-images.githubusercontent.com/34663130/36202269-ee9adf10-11a4-11e8-856d-fdf73446ed4b.png)

The result is OK. The ok = true. PlaceOrder in MT5 is OK. The result variable is null.
