### ISSUE TITLE
What is different between QuoteUpdate     MT4<->MT5

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#87]
I get an error from Matlab when I want to add the quotelistener.
The other two event handler can be connected (ConnectionStateChanged,QuoteAdded)
The call is the same as under MT4-Api or not?
Matlab error: "**.NET events with nonstandard delegate definition are not supported in MATLAB.**"

Mt4:

![image](https://user-images.githubusercontent.com/17534012/36344215-3c87fd4c-1417-11e8-8bea-bff95fc0244f.png)

Mt5:

![image](https://user-images.githubusercontent.com/17534012/36344269-f2a24a9c-1417-11e8-87c2-7495235079fd.png)

**Comment by vdemydiuk** [comment]
I have added event QuoteUpdate to MtApi5Client that is working like MT4 client now. So it can be easy used in MATLAB.
I will update MATLAB examples for MT5 and will create new release 1.0.16 soon,

**Comment by KptKuck** [comment]
Thank you for your fast reaction, great work !
