### ISSUE TITLE
Tester Mode MT5:  Why is not currently activated? 

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#88]
In the current version 1.4 MtApi5.mq5 the Tester Mode is not active.
I know that in the tester the function OnTimer () does not work. But by a small change, he actually works well. Or are there any difficulties with this type of implementation?

> void OnTick()
{
   start();
   if (IsTesting()) OnTimer();
}

**Comment by vdemydiuk** [comment]
I need to investigate this issue, I will answer on it later.

**Comment by vdemydiuk** [comment]
Yes, your fix must work correct for backtesting. MT4 expert has the same functionality. I have forgotten to add it into MT5 expert.
I will fix it in 1.0.16.
