### ISSUE TITLE
Bug in function ParseResult MqlTradeResult

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#89]
After conversation from string to double the double value are not dot separeted.

![image](https://user-images.githubusercontent.com/17534012/36355501-8469e4c2-14e4-11e8-96ec-3f8014f23fcd.png)

**Comment by KptKuck** [comment]
I experimented a bit and with the change the double value is now separated. With a comma, but better than without.

![image](https://user-images.githubusercontent.com/17534012/36356654-3540d6b0-14f5-11e8-8fb6-58c32723e55e.png)

**Comment by vdemydiuk** [comment]
Hi.
yes, you are right. There is a bug. I have found it working on issue #82. I will release fix soon.
