### ISSUE TITLE
TimeCurrent() в МТ5

### ISSUE THREAD

**Issue by cia76** [vdemydiuk/mtapi#90]
Вячеслав, большое спасибо за ваши труды! В МТ4 есть очень полезная функция MTApiClient.TimeCurrent(); Она очень помогает при синхронизации локального времени с терминалом МТ4. Можно ли сделать подобную функцию для терминала МТ5?

**Comment by vdemydiuk** [comment]
Будет добавлено в версию 1,0,16.
Спасибо.
