### ISSUE TITLE
MT5 - MarketBookGet Error

### ISSUE THREAD

**Issue by marcopipino** [vdemydiuk/mtapi#91]
Hi,
When i execute MarketBookGet only first element is filled on array , the others came null .
![error](https://user-images.githubusercontent.com/33042580/36426617-5ae12aa2-1629-11e8-8e15-a397fb5b6df1.gif)

**Comment by vdemydiuk** [comment]
There is very very stupid mistake in code of function MarketBookGet (MtApi5Client);
               foreach (var t in retVal)
                {
                     **book[0]** = new MqlBookInfo((ENUM_BOOK_TYPE)t.type, t.price, t.volume);
                }
I will fix it in version 1.0.17.
