### ISSUE TITLE
An exception of type 'MtApi.MtExecutionException' occurred in MtApi.dll but was not handled in user code

### ISSUE THREAD

**Issue by grimlis** [vdemydiuk/mtapi#97]
hello;
i'm connected in my platform mt4 and mt5 but after start project 10 secend some error come like this plz check below and thank you.
![1](https://user-images.githubusercontent.com/35891320/37003012-79662852-20c3-11e8-9393-f589f3f5c1d1.PNG)
[20180305.log](https://github.com/vdemydiuk/mtapi/files/1782830/20180305.log)

**Comment by vdemydiuk** [comment]
Hello.
Can you provide full stack of the exception and what command (function) of MtApi was executed? It is difficult to understand what reason of the problem from your picture.
Also I want clarify that MtExecutionException is using to perform errors from MT side during execution MtApi functions.

**Comment by grimlis** [comment]
ok my friend 
![2](https://user-images.githubusercontent.com/35891320/37033004-4627486c-213c-11e8-9cf0-dbd4277bb3ca.PNG)
![3](https://user-images.githubusercontent.com/35891320/37033005-4651268c-213c-11e8-91af-edbb76ddc63c.PNG)
![4](https://user-images.githubusercontent.com/35891320/37033007-4677442a-213c-11e8-8da5-c3c46c3ce8ed.PNG)
