### ISSUE TITLE
Passing System.String Error

### ISSUE THREAD

**Issue by KptKuck** [vdemydiuk/mtapi#99]
I have problems in Matlab to pass a string to the MtApi5.
When I use Ordersend it works (request.symbol). That's a System.String

But if I use SymbolSelect (string symbolName, bool selected) and I pass a SystemString I get a "matching signature error"

> >> symbolToPass = System.String('EURUSD');
>> cApiResult = api.cMarketInfo.SymbolSelect(symbolToPass,true);
94          if self.cMt5Api.h.SymbolName(symbolName,selected)     
No method 'SymbolName' with matching signature found for class 'MtApi5.MtApi5Client'.
 

I have already tried as a normal string, no success.
Also as a char, no success.

What's the difference ?

**Comment by KptKuck** [comment]
Update:
I tested the SymbolIsSyncronized function with same System.String -> No passing Error

``    function Test_SymbolIsSynchronized()
        
        symbol = System.String('EURUSD');      
        cApiResult = apiTester.cMarketInfo.SymbolIsSynchronized(symbol);   
        
        if cApiResult.isSuccess()
            apiTester.cLogger.trace('SymbolIsSynchronized: OK');
            apiTester.cLogger.trace(strcat('Result: ',string(cApiResult.Bool)));
        else
             apiTester.cLogger.error('SymbolIsSynchronized: Error');
        end
      
    end

**Comment by vdemydiuk** [comment]
I will investigate this problem.

**Comment by vdemydiuk** [comment]
I have tried to test function SymbolSelect in MATLAB sample and have not got any errors like "matching signature error".
This is my test function:
    function testSelectSymbol(self)
        symbol = char('EURUSD');
        result = self.h.SymbolSelect(symbol, true);
        fprintf('SelectSymbol: result = %d \n', result);
    end

Console output: 
SelectSymbol: result = 1 

So I am not sure that there is the problem in MtApi.

**Comment by KptKuck** [comment]
ok ,i will check this example

**Comment by KptKuck** [comment]
Ok, your example works for me too. It probably depends on Matlab, which I do not understand. I'll investigate that. Other functions that I use work. Very strange.

**Comment by KptKuck** [comment]
I use the Api in the same way in my API. Here are both functions:
The first one does not work. The second one works.
Maybe someone else has a tip.

![grafik](https://user-images.githubusercontent.com/17534012/37108331-1e30a03c-2237-11e8-8c0e-dc494ae9f98b.png)

**Comment by vdemydiuk** [comment]
Maybe there is the problem with calling function SymbolName from function SymbolSelect. I can assume that MatLab is trying to call function SymbolName that is defined upper and not same function from the MtApi. I recommend you to set names of your functions with some differences (for example, Mt5SymbolName).

**Comment by KptKuck** [comment]
Ohh, that's embarrassing :-) ... I found my mistake. "Sometimes you do not see the forest for the trees" .. German proverb.

The Api call is a completely different one.

![image](https://user-images.githubusercontent.com/17534012/37162272-21a4b276-22f5-11e8-8ab6-09925404565a.png)
